import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import postcss from "postcss";

// Project root (where the command is executed)
const ROOT_DIR = process.cwd();

// styles/
const STYLES_DIR = path.join(ROOT_DIR, "src", "styles");

// Raw, hand-edited tweakcn themes.
const THEMES_DIR = path.join(STYLES_DIR, "themes");

// Generated build artifacts.
const GENERATED_DIR = path.join(STYLES_DIR, ".generated");
const GENERATED_THEMES_DIR = path.join(GENERATED_DIR, "themes");

const scopeThemeCss = (name: string, css: string): string => {
  const root = postcss.parse(css);
  let matched = false;

  root.each((node) => {
    if (node.type !== "rule") return;

    const selector = node.selector.trim();

    if (selector === ":root") {
      node.selector = `[data-theme="${name}"]`;
      matched = true;
    } else if (selector === ".dark") {
      node.selector = `[data-theme="${name}"].dark`;
      matched = true;
    }
  });

  if (!matched) {
    console.warn(
      `[themes] ${name}.css has no top-level :root or .dark rule to scope — copied as-is.`,
    );
  }

  return root.toString();
};

const run = async () => {
  const entries = await readdir(THEMES_DIR, { withFileTypes: true });

  const themeFiles = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".css"))
    .map((entry) => entry.name)
    .sort();

  if (themeFiles.length === 0) {
    console.warn(`[themes] No .css files found in ${THEMES_DIR}`);
    return;
  }

  await mkdir(GENERATED_THEMES_DIR, { recursive: true });

  for (const fileName of themeFiles) {
    const themeName = path.parse(fileName).name;

    const rawCss = await readFile(path.join(THEMES_DIR, fileName), "utf8");

    const scopedCss = scopeThemeCss(themeName, rawCss);

    await writeFile(
      path.join(GENERATED_THEMES_DIR, fileName),
      scopedCss,
      "utf8",
    );

    console.log(`[themes] Generated ${fileName} → [data-theme="${themeName}"]`);
  }

  const aggregator = [
    "/* AUTO-GENERATED by build-themes.ts. Do not edit. */",
    ...themeFiles.map((file) => `@import "./themes/${file}";`),
    "",
  ].join("\n");

  await writeFile(
    path.join(GENERATED_DIR, "theme-imports.css"),
    aggregator,
    "utf8",
  );

  console.log(
    `[themes] Wrote theme-imports.css (${themeFiles.length} theme(s))`,
  );
};

run().catch((error) => {
  console.error("[themes] Failed to build themes:", error);
  process.exit(1);
});
